### ISSUE TITLE
no std support? + specify Cargo.toml in README

### ISSUE THREAD

**Issue by black-sabbath** [Stebalien/horrorshow-rs#21]
Problem One: I need to know if this crate can be used in a project that is run with `#![no_std]`. 
Problem Two: You should probably put how to add the crate to your Cargo.toml in the README. I had to dig through the horrorshow.rs Cargo.toml file to find the version.

Just some suggestions (and a question). 😺

**Comment by Stebalien** [comment]
1. Not at the moment. It should be possible but would require a bit of reworking to carve out the parts that don't depend on std.
2. I've never really understood the point of that. Is it really that useful? Personally, I just lookup the crate on crates.io or use the `cargo add` command (`cargo install cargo-add`) to install dependencies. Putting the crate version in the README means I need to update it every time I release a new version (which I'll assuredly forget to do).

**Comment by black-sabbath** [comment]
True.
