### ISSUE TITLE
escaping converts foreign letters to &lt; &gt;

### ISSUE THREAD

**Issue by ben0x539** [Stebalien/horrorshow-rs#25]
```rust
fn main() {
    use horrorshow::{*, helper::doctype};
    println!("{}", html!{ : "м, о"; })
}
```

outputs `&lt;, &gt;`.

I think it's because we're [truncating `char`s to `u8`s here](https://github.com/Stebalien/horrorshow-rs/blob/f255be57f0544107df05689d7fcbf90241be481e/src/template.rs#L214).

**Comment by Stebalien** [comment]
Yep, thanks for catching this!
