### ISSUE TITLE
Add #[macro_export(local_inner_macros)] attribute to support Rust 2018

### ISSUE THREAD

**Issue by lfairy** [Stebalien/horrorshow-rs#26]
Rust 2018 lets us import macros in a nice way (`use horrorshow::html;`), but the macro author has to opt into this behavior themselves.

I think it should be enough to add `#[macro_export(local_inner_macros)]` to every macro definition in the crate, but I'd test first to be sure.

See: https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#local-helper-macros

**Comment by Stebalien** [comment]
Thanks!
