### ISSUE TITLE
Indenting/reformatting in IntelliJ doesn't fix indentation

### ISSUE THREAD

**Issue by yatesco** [Stebalien/horrorshow-rs#32]
<newbie/>

If I reformat the document in Intellij, it doesn't fix the indentation within the macro, so if I start with:

``` rust
        pub(crate) mod table {
        use horrorshow::prelude::*;
        use horrorshow::helper::doctype;

        pub(crate) fn render() -> Box<horrorshow::RenderBox> {
            box_html! {
        table {
            thead {
             tr {
                th {: "Column 1"}
                th {: "Column 1"}
                th {: "Column 1"}
                }
            }
                        tbody {
                        tr {
                td {: "Data 1"}
                td {: "Data 1"}
                td {: "Data 1"}
                }
            }
            }

           label(typ="text", name="name");
           : "First criteria"
    }
        }
    }
```

and then ask IntelliJ for reformat, it doesn't change it at all. I am also not getting any errors inline until I manually ask it to compile/build.

Is this expected and simply a price of using Rust's macros? or have I missed something?

(it's a price well paid as the compile time safety is great!)

**Comment by Stebalien** [comment]
I believe IntelliJ uses rustfmt and rustfmt ignores macros as it has no idea how to format them. Honestly, it probably never _will_ format macros.

Note: Some editors (e.g., emacs) will do this for you using generic bracket-based format rules. However, those rules aren't guaranteed to get anything right as nothing really _defines_ what's "right" in this case.

**Comment by yatesco** [comment]
No worries - thanks @Stebalien
