### ISSUE TITLE
HTML boolean attribute support?

### ISSUE THREAD

**Issue by sezna** [Stebalien/horrorshow-rs#33]
I'm unclear on whether or not horrorshow supports boolean attributes, like `required`:

```
<input type="text" value="value" required />
```

I tried assigning it a boolean value but `bool` doesn't implement `RenderOnce` so that didn't work.

Thanks!

**Comment by Stebalien** [comment]
```
html! {
  input(type="text", value="value", required? = someCondition);
}
```

All the attribute variants are documented here: https://docs.rs/horrorshow/0.7.0/horrorshow/#usage (but could probably use some organization).
