### ISSUE TITLE
Pretty output?

### ISSUE THREAD

**Issue by dashed** [Stebalien/horrorshow-rs#6]
For deeply nested horrorshow templates, it may be useful to have a pretty html output (i.e. space/tabs). Would this be something that may be added to horrorshow-rs?

For now I'm relying on chrome devtools.

**Comment by dashed** [comment]
I tried looking at the macros to see if this is a trivial feature. Might need for a `pretty_html!` macro or something.

**Comment by Stebalien** [comment]
Unfortunately, in HTML, whitespace is sometimes significant and sometimes not. For example, indents in pre elements will be preserved and some elements will even preserve leading/trailing newlines (depending on the CSS). Horrorshow doesn't actually understand the HTML spec so it has no way to know when it can add indents/newlines and when it can't. It's probably better to just run the resulting html through an actual HTML parser and asking that to pretty print.

**Comment by dashed** [comment]
Ah I forgot about that case. 

I looked at the `html5ever` crate to see if it can pretty output; but it doesn't seem like it can (as of June 2, 2016).

I'll close this issue as this is probably out of scope for horrowshow.
